name: Build Kernel

on:
  push:
    paths:
      - '.github/workflows/build-kernel.yml'
  workflow_dispatch:

jobs:
  build:
    name: Build Kernel
    runs-on: ubuntu-24.04
    steps:

      - name: Checkout
        uses: actions/checkout@v7

      - name: Cache
        id: cache
        uses: actions/cache@v6
        with:
          path: gcc-linaro-7.3.1-2018.05-x86_64_aarch64-linux-gnu
          key: gcc-linaro-7.3.1-2018.05-x86_64_aarch64-linux-gnu

      - name: Install toolchain
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          curl -fL -o gcc-linaro-7.3.1-2018.05-x86_64_aarch64-linux-gnu.tar.xz \
            https://mirror-us-stl1.armbian.airframes.io/dl/_toolchain/gcc-linaro-7.3.1-2018.05-x86_64_aarch64-linux-gnu.tar.xz

          file gcc-linaro-7.3.1-2018.05-x86_64_aarch64-linux-gnu.tar.xz

          tar -xJf gcc-linaro-7.3.1-2018.05-x86_64_aarch64-linux-gnu.tar.xz

      - name: Build kernel
        run: |
          echo "commit=$(echo ${{ github.sha }} | cut -c 1-7)" >> $GITHUB_ENV

          TOOLCHAIN="$(pwd)/gcc-linaro-7.3.1-2018.05-x86_64_aarch64-linux-gnu/bin/aarch64-linux-gnu-"

          echo "Toolchain: ${TOOLCHAIN}"
          ls -l "${TOOLCHAIN}gcc"
          "${TOOLCHAIN}gcc" --version

          make ARCH=arm64 CROSS_COMPILE="${TOOLCHAIN}" RK3399_IMT_defconfig
          make ARCH=arm64 CROSS_COMPILE="${TOOLCHAIN}" -j8
          make ARCH=arm64 CROSS_COMPILE="${TOOLCHAIN}" rk3399-tve1030g_IMT.img

      - name: Build modules
        run: |
          TOOLCHAIN="$(pwd)/gcc-linaro-7.3.1-2018.05-x86_64_aarch64-linux-gnu/bin/aarch64-linux-gnu-"

          mkdir -p modules
          make ARCH=arm64 CROSS_COMPILE="${TOOLCHAIN}" modules
          make ARCH=arm64 CROSS_COMPILE="${TOOLCHAIN}" \
            INSTALL_MOD_PATH=modules \
            INSTALL_MOD_STRIP=1 \
            modules_install
            
      - name: Upload
        uses: actions/upload-artifact@v7
        with:
          name: zmooth-kernel@${{ env.commit }}
          path: |
            arch/arm64/boot/Image
            arch/arm64/boot/dts/rockchip/**
            vmlinux
            **.img
            modules/**
          if-no-files-found: ignore
